% -------------------------------------------------------------------
%  Generated by MATLAB on 3-Oct-2023 07:50:39
%  MATLAB version: 9.14.0.2337262 (R2023a) Update 5
% -------------------------------------------------------------------
saveVarsMat = load('Coriolis.mat');

C = saveVarsMat.C; % <1x1 sym> unsupported class

clear saveVarsMat;
