function qpp = qpp(Izz1,Izz2,g,l1,lc1,lc2,m1,m2,q1,q2,qp1,qp2,t1,t2)
%QPP
%    QPP = QPP(Izz1,Izz2,G,L1,LC1,LC2,M1,M2,Q1,Q2,QP1,QP2,T1,T2)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    05-Oct-2023 00:33:30

t4 = cos(q1);
t5 = cos(q2);
t6 = sin(q2);
t7 = q1+q2;
t8 = l1.^2;
t9 = lc1.^2;
t10 = lc2.^2;
t11 = lc2.^3;
t12 = m2.^2;
t13 = q2.*2.0;
t14 = qp1.^2;
t15 = qp2.^2;
t16 = sin(t13);
t17 = cos(t7);
t18 = l1.*lc2.*m2.*t2.*t5.*2.0;
t20 = t8.*t10.*t12;
t21 = g.*l1.*t4.*t10.*t12;
t19 = -t18;
t22 = -t21;
t23 = t14.*t16.*t20;
et1 = 1.0./(t20-t5.^2.*t20+Izz1.*Izz2+Izz2.*m1.*t9+Izz2.*m2.*t8+Izz1.*m2.*t10+m1.*m2.*t9.*t10);
et2 = -(t19+t22+t23-Izz1.*t2+Izz2.*t1-Izz2.*t2-m1.*t2.*t9-m2.*t2.*t8+m2.*t1.*t10-m2.*t2.*t10+(t15.*t16.*t20)./2.0+qp1.*qp2.*t16.*t20-Izz2.*g.*l1.*m2.*t4-Izz2.*g.*lc1.*m1.*t4+Izz1.*g.*lc2.*m2.*t17+l1.*lc2.*m2.*t1.*t5+g.*lc2.*t8.*t12.*t17+l1.*t6.*t11.*t12.*t14+l1.*t6.*t11.*t12.*t15+l1.^3.*lc2.*t6.*t12.*t14+g.*l1.*t5.*t10.*t12.*t17-g.*lc2.*t4.*t5.*t8.*t12+l1.*qp1.*qp2.*t6.*t11.*t12.*2.0+Izz1.*l1.*lc2.*m2.*t6.*t14+Izz2.*l1.*lc2.*m2.*t6.*t14+Izz2.*l1.*lc2.*m2.*t6.*t15-g.*lc1.*m1.*m2.*t4.*t10+g.*lc2.*m1.*m2.*t9.*t17+Izz2.*l1.*lc2.*m2.*qp1.*qp2.*t6.*2.0+l1.*lc2.*m1.*m2.*t6.*t9.*t14-g.*l1.*lc1.*lc2.*m1.*m2.*t4.*t5);
qpp = [(t19+t22+t23+Izz2.*t1.*2.0-Izz2.*t2.*2.0+m2.*t1.*t10.*2.0-m2.*t2.*t10.*2.0-Izz2.*g.*l1.*m2.*t4.*2.0-Izz2.*g.*lc1.*m1.*t4.*2.0+l1.*t6.*t11.*t12.*t14.*2.0+l1.*t6.*t11.*t12.*t15.*2.0+g.*l1.*t10.*t12.*cos(q2+t7)+l1.*qp1.*qp2.*t6.*t11.*t12.*4.0+Izz2.*l1.*lc2.*m2.*t6.*t14.*2.0+Izz2.*l1.*lc2.*m2.*t6.*t15.*2.0-g.*lc1.*m1.*m2.*t4.*t10.*2.0+Izz2.*l1.*lc2.*m2.*qp1.*qp2.*t6.*4.0)./(t20-t20.*cos(t13)+Izz1.*Izz2.*2.0+Izz2.*m1.*t9.*2.0+Izz2.*m2.*t8.*2.0+Izz1.*m2.*t10.*2.0+m1.*m2.*t9.*t10.*2.0);et1.*et2];
end
